### ISSUE TITLE
Setting sidqkiq uid/gid via config

### ISSUE THREAD

**Issue by KateWilkins** [FlavourSys/sidekiq-runner#7]
Is there any way to set the sidekiq task uid/gid? Thanks.

**Comment by maltoe** [comment]
Hi Kate!

No, unfortunately there's no such option currently. Though, God has support for setting uid/gid of the process. The easiest way would be to make `uid` + `gid` additional options in [sidekiq_instance.rb](https://github.com/FlavourSys/sidekiq-runner/blob/5d128579988f8ab78c47118e484b2cecfdc29623/lib/sidekiq-runner/sidekiq_instance.rb) (`CONFIG_FILE_ATTRIBUTES`) and evaluate them in the [sidekiq.god](https://github.com/FlavourSys/sidekiq-runner/blob/5d128579988f8ab78c47118e484b2cecfdc29623/lib/sidekiq-runner/sidekiq.god) script. Another (imho better) option would be to add a config option *block* that would be `instance_eval`'d in the god script, so the user could set arbitrary options, instead of us having to make each and every option available through Sidekiq-Runner.

PRs welcome!

**Comment by maltoe** [comment]
Kate, nevermind the block stuff. I just went ahead and added a PR for the easy implementation. Would you be so kind to test this?

**Comment by KateWilkins** [comment]
Hi,
Many thanks for that I'd literally just forked and was about to do the same thing. I've tested your change and its working fine. Thanks.
